FROM alpine:3.21

ARG MIGRATE_VERSION=v4.18.3

RUN apk add --no-cache curl \
    && curl -fsSL "https://github.com/golang-migrate/migrate/releases/download/${MIGRATE_VERSION}/migrate.linux-amd64.tar.gz" \
       | tar -xz -C /usr/local/bin \
    && chmod +x /usr/local/bin/migrate \
    && apk del curl

COPY migrations /migrations

ENTRYPOINT ["migrate", "-path", "/migrations", "-database"]
CMD ["help"]
